### ISSUE TITLE
Mainteinance

### ISSUE THREAD

**Issue by zamber** [jgoldschrafe/puppet-selinux_types#11]
Hi, is this repo still maintained? My PR is standing for over a year now and last changes were done over 2 years ago. If you abandoned it please call out to other contributors for a maintainer.

**Comment by jgoldschrafe** [comment]
I informally turned this over to https://github.com/blentz/puppet-selinux_types some time ago, but it looks like that fork hasn't been updated in some time either. You might check with him to see if he's still interested in maintaining this.
